name: Create the DEB

permissions:
  contents: write

on:
  push:

jobs:
  Create_Packages:
    name: Create Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: "REPO"

      - name: Copy script files around to stop .github from being added to the package then build the package
        run: |
          mkdir PKG_SOURCE
          cp -Rf REPO/etc REPO/DEBIAN PKG_SOURCE
          dpkg-deb --build PKG_SOURCE usbtmc-rules.deb

      - name: Release the Package
        uses: softprops/action-gh-release@v1
        with:
          files: usbtmc-rules.deb